# Generated by Django 4.2.2 on 2023-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labanmanagement', '0002_expenditure_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenditure',
            old_name='paritculars',
            new_name='particulars',
        ),
        migrations.AlterField(
            model_name='revenue',
            name='revenue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=100),
        ),
    ]
